# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: dollar_cource.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class DollarcourseServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/.Dollarcourse"
		self._endpoints = {
			"GetCourse": Endpoint(
				service_name="Dollarcourse",
				name="GetCourse",
				function=getattr(service, "GetCourse"),
				input=_sym_db.GetSymbol("Mes"),
				output=_sym_db.GetSymbol("Course"),
			),
		}

class DollarcourseClient(TwirpClient):

	def GetCourse(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/.Dollarcourse/GetCourse",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("Course"),
			**kwargs,
		)
