# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dollar_cource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dollar_cource.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x64ollar_cource.proto\"\x05\n\x03Mes\"\x17\n\x06\x43ourse\x12\r\n\x05price\x18\x01 \x01(\x02\x32*\n\x0c\x44ollarcourse\x12\x1a\n\tGetCourse\x12\x04.Mes\x1a\x07.Courseb\x06proto3'
)




_MES = _descriptor.Descriptor(
  name='Mes',
  full_name='Mes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=28,
)


_COURSE = _descriptor.Descriptor(
  name='Course',
  full_name='Course',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='Course.price', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Mes'] = _MES
DESCRIPTOR.message_types_by_name['Course'] = _COURSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mes = _reflection.GeneratedProtocolMessageType('Mes', (_message.Message,), {
  'DESCRIPTOR' : _MES,
  '__module__' : 'dollar_cource_pb2'
  # @@protoc_insertion_point(class_scope:Mes)
  })
_sym_db.RegisterMessage(Mes)

Course = _reflection.GeneratedProtocolMessageType('Course', (_message.Message,), {
  'DESCRIPTOR' : _COURSE,
  '__module__' : 'dollar_cource_pb2'
  # @@protoc_insertion_point(class_scope:Course)
  })
_sym_db.RegisterMessage(Course)



_DOLLARCOURSE = _descriptor.ServiceDescriptor(
  name='Dollarcourse',
  full_name='Dollarcourse',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=55,
  serialized_end=97,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCourse',
    full_name='Dollarcourse.GetCourse',
    index=0,
    containing_service=None,
    input_type=_MES,
    output_type=_COURSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOLLARCOURSE)

DESCRIPTOR.services_by_name['Dollarcourse'] = _DOLLARCOURSE

# @@protoc_insertion_point(module_scope)
